sudo: required

services:
  - docker

env:
  matrix:
    - TEST_SUITE=medium
    - TEST_SUITE=sql

before_script:
  - docker build -t cubridci docker/ci

script:
  - docker run -e MAKEFLAGS="-j2" -e TEST_SUITE=$TEST_SUITE cubridci

