version: '2'

services:
  checkout:
    image: alpine
    working_dir: /home/cubrid
    command: >
      sh -c "apk add --no-cache git \
        && git clone --depth 1 https://github.com/CUBRID/cubrid \
        && git clone --depth 1 https://github.com/CUBRID/cubrid-testtools \
        && git clone --depth 1 https://github.com/CUBRID/cubrid-testcases"
    volumes:
      - cubrid:/home/cubrid
      - CUBRID:/home/CUBRID
  build:
    build: ./build
    volumes_from:
      - checkout
  test:
    build: ./test
    volumes_from:
      - checkout

volumes:
  cubrid: {}
  CUBRID: {}
